name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    #1. 코드 가져오기
    - uses: actions/checkout@v3

    #2. 자바 17 설치
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    #3. Gradle 권한 부여
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    #4. 스프링 부트 빌드
    - name: Build with Gradle
      run: ./gradlew bootJar

    #5. Docker Hub 로그인
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  #구글로그인 사용자는 닉네임이 username일수있음
        password: ${{ secrets.DOCKER_PASSWORD }}

    #6. Docker 이미지 빌드 및 푸시
    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/ticketing-server:latest

    #7. 서버 접속 배포
    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          docker compose pull app
          docker compose up -d app
          docker image prune -f